"""Recursive rule set for street networks and parcel division.

Streets are generated by recursively cutting a district in two: at
each step a straight street of a given width is laid across the
current region along its longer axis, at a ratio drawn from a seeded
random source, and the two remaining strips on either side are
recursed into again. Recursion stops once the maximum depth is
reached, or a candidate cut would leave a strip smaller than the
configured minimum block size, at which point that strip is kept
whole as a block.

This is documented in docs/algorithm-notes.md as a deliberate stand in
for a turtle graphics L-system: a small set of production rules
(cut the region, recurse into what remains) applied recursively, which
is the same generative idea an L-system encodes, but one that keeps
the network strictly rectilinear and therefore easy to reason about
and test, rather than producing organically branching roads.

Once the street cuts settle the district into blocks, each block is
subdivided again, this time with no street gap between the pieces,
into individual parcels using the same subdivide_rect primitive that
citygen.shape_grammar uses for rooms.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass

from citygen.shape_grammar import Rect, subdivide_rect


@dataclass(frozen=True)
class StreetSegment:
    """A straight street segment.

    Attributes:
        start: One endpoint, as an (x, y) pair.
        end: The other endpoint, as an (x, y) pair.
        width: The street's width.
    """

    start: tuple[float, float]
    end: tuple[float, float]
    width: float

    @property
    def length(self) -> float:
        return math.dist(self.start, self.end)


@dataclass(frozen=True)
class StreetRules:
    """Parameters controlling how a district is cut into blocks.

    Attributes:
        min_block_width: Smallest allowed width for a block.
        min_block_height: Smallest allowed height for a block.
        max_depth: Maximum number of recursive street cuts along any branch.
        street_width: Width of every generated street.
        split_ratio_range: Inclusive range the cut position is drawn
            from, as a fraction of the axis being cut.
    """

    min_block_width: float
    min_block_height: float
    max_depth: int
    street_width: float
    split_ratio_range: tuple[float, float] = (0.4, 0.6)


@dataclass(frozen=True)
class ParcelRules:
    """Parameters controlling how a block is subdivided into parcels.

    Attributes:
        min_parcel_width: Smallest allowed width for a parcel.
        min_parcel_height: Smallest allowed height for a parcel.
        max_depth: Maximum number of recursive splits along any branch.
        split_ratio_range: Inclusive range the split position is drawn
            from, as a fraction of the axis being split.
    """

    min_parcel_width: float
    min_parcel_height: float
    max_depth: int
    split_ratio_range: tuple[float, float] = (0.3, 0.7)


@dataclass(frozen=True)
class StreetNetwork:
    """The generated network for one district.

    Attributes:
        streets: Every street segment cut while dividing the district.
        blocks: The regions left over between streets.
        parcels: Every block subdivided into individual parcels, flattened
            into a single list. Parcels from the same block are adjacent
            in this list but the boundary between blocks is not marked,
            since nothing downstream currently needs it.
    """

    streets: list[StreetSegment]
    blocks: list[Rect]
    parcels: list[Rect]


def generate_street_network(
    district: Rect,
    street_rules: StreetRules,
    parcel_rules: ParcelRules,
    seed: int,
) -> StreetNetwork:
    """Cuts a district into blocks with streets, then blocks into parcels.

    Args:
        district: The area to lay streets through.
        street_rules: Constraints on block size, street width, recursion
            depth, and cut ratio.
        parcel_rules: Constraints on parcel size, recursion depth, and
            split ratio, applied independently within each block.
        seed: Random seed. The same seed, district, and rules always
            produce the same network.

    Returns:
        A StreetNetwork with the generated streets, blocks, and parcels.
    """
    rng = random.Random(seed)

    streets: list[StreetSegment] = []
    blocks: list[Rect] = []
    _lay_streets(district, street_rules, rng, depth=0, streets=streets, blocks=blocks)

    parcels: list[Rect] = []
    for block in blocks:
        parcels.extend(
            subdivide_rect(
                block,
                parcel_rules.min_parcel_width,
                parcel_rules.min_parcel_height,
                parcel_rules.max_depth,
                parcel_rules.split_ratio_range,
                rng,
            )
        )

    return StreetNetwork(streets=streets, blocks=blocks, parcels=parcels)


def _lay_streets(
    rect: Rect,
    rules: StreetRules,
    rng: random.Random,
    depth: int,
    streets: list[StreetSegment],
    blocks: list[Rect],
) -> None:
    if depth >= rules.max_depth:
        blocks.append(rect)
        return

    split_along_x = rect.width >= rect.height
    ratio = rng.uniform(*rules.split_ratio_range)
    half_street = rules.street_width / 2

    if split_along_x:
        offset = rect.width * ratio
        first = Rect(rect.x, rect.y, offset - half_street, rect.height)
        second = Rect(
            rect.x + offset + half_street,
            rect.y,
            rect.width - offset - half_street,
            rect.height,
        )
        street_x = rect.x + offset
        street = StreetSegment((street_x, rect.y), (street_x, rect.y + rect.height), rules.street_width)
    else:
        offset = rect.height * ratio
        first = Rect(rect.x, rect.y, rect.width, offset - half_street)
        second = Rect(
            rect.x,
            rect.y + offset + half_street,
            rect.width,
            rect.height - offset - half_street,
        )
        street_y = rect.y + offset
        street = StreetSegment((rect.x, street_y), (rect.x + rect.width, street_y), rules.street_width)

    children = [first, second]
    if any(child.width < rules.min_block_width or child.height < rules.min_block_height for child in children):
        blocks.append(rect)
        return

    streets.append(street)
    for child in children:
        _lay_streets(child, rules, rng, depth + 1, streets, blocks)
